### ISSUE TITLE
How to format my own images to match the MNIST Dataset?

### ISSUE THREAD

**Issue by zhuqunxi** [facebookresearch/qmnist#2]
Dear friend, 

How to format my own images (such as the following image) to match the MNIST Dataset?   Thanks.
![image](https://user-images.githubusercontent.com/22273557/163765530-a8662d3d-aae4-4db8-8eff-8d3c09971cfd.png)

**Comment by leonbottou** [comment]
This is not really an issue with the qmnist dataset and code.

I suggest you read the paper.  Then you can check function `fim_mnist_prepro` at https://github.com/facebookresearch/qmnist/blob/7f80561a0accbbf7b53764431867df233e33ffdc/making_qmnist/xnist.lsh#L360 which takes a floating point image (a float tensor hxwx3) and produces a unsigned byte image (a uint8 tensor 28x28x3) that can then be written into a mnist-like image file with function `save-idx3-ubyte`.  This function rescales, recenters, and discretize in a way that we believe is quite close to what was done with mnist.

Now all this is written in Lush which is a deep learning framework that predates PyTorch by two or three decades (and even predates Python by one decade). It is superficially very different but was largely copied in further frameworks (e.g. the use of tensors, the tensor compiler design, etc.)  You can learn about lush at  lush.sf.net.
