### ISSUE TITLE
What does the Q stands for?

### ISSUE THREAD

**Issue by arturandre** [facebookresearch/qmnist#3]
Sorry if I missed it, but I couldn't find it.

**Comment by leonbottou** [comment]
Q used to stand for Quasi as in Quasi-MNIST because, initially, the reconstruction was less accurate than it is now.
The paper has a couple paragraph about the reconstruction process https://proceedings.neurips.cc/paper/2019/hash/51c68dc084cb0b8467eafad1330bce66-Abstract.html
